name: Firebase Deploy Action
description: Build APK and upload it to Firebase App Distribution.
inputs:
  firebase-service-account:
    description: 'Firebase Service Account JSON'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build APK
      shell: bash
      run: ./gradlew assembleRelease --build-cache --no-daemon

    - name: Upload APK to Firebase App Distribution
      shell: bash
      run: ./gradlew appDistributionUploadRelease --build-cache --no-daemon
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json