name: Publish to Firebase App Distribution

on:
  push:
    branches:
      - main
      - firebase

jobs:
  build:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "Error: FIREBASE_SERVICE_ACCOUNT secret is not set."
            exit 1
          fi
#
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 17
#          cache: gradle
#
#      - name: Build APK
#        run: ./gradlew assembleRelease --build-cache --no-daemon

      - name: Create Firebase Service Account Credentials File
        env:
          JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "$JSON" > ${{ runner.temp }}/firebase-service-account.json

      - name: Print Firebase Service Account Credentials File
        run: cat "${{ runner.temp }}/firebase-service-account.json"

      - name: Check Temporary File Permissions
        run: |
          if [ -r ${{ runner.temp }}/firebase-service-account.json ]; then
            echo "Temporary file has read permissions."
          else
            echo "Temporary file does not have read permissions."
            exit 1
          fi
#
#      - name: Upload APK to Firebase App Distribution
#        run: ./gradlew appDistributionUploadRelease --build-cache --no-daemon
#        env:
#          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json  # Set the env variable here