name: Publish to Firebase App Distribution

on:
  push:
    branches:
      - main
      - firebase

jobs:
  build:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "Error: FIREBASE_SERVICE_ACCOUNT secret is not set."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use GOOGLE_APPLICATION_CREDENTIALS in expression
        run: echo "This is the value ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"

#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 17
#          cache: gradle
#
#      - name: Build APK
#        run: ./gradlew assembleRelease --build-cache --no-daemon

      - name: Create Firebase Service Account Credentials File
        run: printf "%s" "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: debug Print GOOGLE_APPLICATION_CREDENTIALS
        run: echo "This is the value $GOOGLE_APPLICATION_CREDENTIALS"

      - name: Print Firebase Service Account Credentials File
        run: cat "$GOOGLE_APPLICATION_CREDENTIALS"
#
#      - name: Upload APK to Firebase App Distribution
#        run: ./gradlew appDistributionUploadRelease --build-cache --no-daemon