name: Publish to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "Error: FIREBASE_SERVICE_ACCOUNT secret is not set."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache Gradle build output
        uses: actions/cache@v3
        with:
          path: |
            **/build
          key: build-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            build-${{ runner.os }}-

      - name: Build APK
        run: ./gradlew assembleRelease --build-cache --no-daemon

      - name: Set up Firebase Service Account Credentials file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-service-account.json
        # This step retrieves the Firebase service account credentials from the GitHub secret
        # and saves it to a file that will be used in the upload step.
      - name: Check File Creation
        run: |
          if [ -f $HOME/firebase-service-account.json ]; then
            echo "File firebase-service-account.json created successfully."
          else
            echo "Error: File firebase-service-account.json not created."
            exit 1
          fi

      - name: Upload APK to Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease --build-cache --no-daemon
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json