name: Publish to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "Error: FIREBASE_SERVICE_ACCOUNT secret is not set."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Deploy to Firebase
        uses: ./.github/actions/firebase-deploy
        with:
          firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
