name: Publish to Firebase App Distribution

on:
  push:
    branches:
      - main
      - firebase

jobs:
  build:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "Error: FIREBASE_SERVICE_ACCOUNT secret is not set."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use GOOGLE_APPLICATION_CREDENTIALS in expression
        run: echo "This is the value ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 17
#          cache: gradle
#
#      - name: Build APK
#        run: ./gradlew assembleRelease --build-cache --no-daemon
#
#
#      - name: Set up Firebase Service Account Credentials file
#        run: |
#          printf "%s" "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" >${{ runner.temp }}/firebase-service-account.json
#        # This step retrieves the Firebase service account credentials from the GitHub secret
#        # and saves it to a file that will be used in the upload step.
#
#      - name: Upload APK to Firebase App Distribution
#        run: ./gradlew appDistributionUploadRelease --build-cache --no-daemon